### ISSUE TITLE
onto-mongo-master_db_1 issue

### ISSUE THREAD

**Issue by sherifyounis** [thdaraujo/onto-mongo#1]
Status: Downloaded newer image for mongo:3.2.8
Creating onto-mongo-master_db_1 ... done                                                                                Creating onto-mongo-master_web_1 ... error                                                                              
ERROR: for onto-mongo-master_web_1  Cannot start service web: Cannot link to a non running container: /onto-mongo-master_db_1 AS /onto-mongo-master_web_1/db

ERROR: for web  Cannot start service web: Cannot link to a non running container: /onto-mongo-master_db_1 AS /onto-mongo-master_web_1/db
ERROR: Encountered errors while bringing up the project.

**Comment by sherifyounis** [comment]
s/onto-mongo-reports$ docker-compose up db
Traceback (most recent call last):
  File "bin/docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 123, in perform_command
  File "compose/cli/command.py", line 69, in project_from_options
  File "compose/cli/command.py", line 125, in get_project
  File "compose/cli/command.py", line 184, in get_project_name
  File "posixpath.py", line 383, in abspath
FileNotFoundError: [Errno 2] No such file or directory
